package rs.highlande.app.tatatu.connection.webSocket

/**
 * File holding reference to all constant values related to both web socket and http protocols.
 * @author mbaldrighi on 2019-07-10.
 */

/***/
const val SERVER_END_POINT_DEBUG = "ws://accessocasa.ddns.net:3030/rtcomttu"
const val SERVER_END_POINT_DEBUG_CHAT = "ws://accessocasa.ddns.net:3031/chatttu"

const val SERVER_END_POINT_DEV = "ws://ttudev.highlanders.app:3030/rtcomttu"
const val SERVER_END_POINT_DEV_3031 = "ws://18.205.151.197:3031/rtcomttu"
const val SERVER_END_POINT_PROD = "wss://websocketttu.highlanders.app/rtcomttu"
const val SERVER_END_POINT_DEV_CHAT = "ws://ttudevchat.highlanders.app:3030/chatttu"
const val SERVER_END_POINT_DEV_CHAT_3031 = "ws://18.205.151.197:3031/chatttu"
const val SERVER_END_POINT_PROD_CHAT = "wss://chat.tatatu.com/chatttu"


const val SERVER_CODE_DB_NAME = "tatatu"

const val SERVER_CODE_NAME = "database"
const val SERVER_CODE_NAME_SUBSCR = "socketsubscription"


const val SERVER_OP_GET_USER = 1003
const val SERVER_OP_MAKE_NEW_FOLLOWER_REQUEST = 1005
const val SERVER_OP_DO_ADD_REMOVE_BLACKLIST = 1006
const val SERVER_OP_SOCKET_SUBSCR = 1008
const val SERVER_OP_MANAGE_FOLLOWER_REQUEST = 1009
const val SERVER_OP_GET_FOLLOW_REQUESTS = 1010
const val SERVER_OP_GET_HOME = 1011
const val SERVER_OP_GET_SUGGESTED = 1012
const val SERVER_OP_GET_FOLLOWERS = 1014
const val SERVER_OP_GET_FOLLOWING = 1015
const val SERVER_OP_DO_SEARCH_FOLLOWING_FOLLOWERS = 1016
const val SERVER_OP_DO_REPORT_USER = 1020
const val SERVER_OP_DO_SHARE_USER_PROFILE = 1021
const val SERVER_OP_GET_TOTAL_FOLLOW_REQUESTS = 1022
const val SERVER_OP_FORGOT_PASSWORD = 1028
const val SERVER_OP_STORE_TOKEN = 1029
const val SERVER_OP_GET_NOTIFICATIONS = 1030
const val SERVER_OP_LOGOUT = 1032
const val SERVER_OP_GET_SUGGESTED_V2 = 1033

const val SERVER_OP_DELETE_POST = 1105
const val SERVER_OP_CREATE_COMMENT = 1107
const val SERVER_OP_GET_TIMELINE = 1109
const val SERVER_OP_DO_LIKE_UNLIKE = 1110
const val SERVER_OP_GET_COMMENTS = 1111
const val SERVER_OP_GET_LIKES = 1113
const val SERVER_OP_DO_COMMENT_LIKE_UNLIKE = 1114
const val SERVER_OP_DO_SHARE_POST = 1115
const val SERVER_OP_DO_REPORT_POST = 1116
const val SERVER_OP_CREATE_POST = 1104
const val SERVER_OP_EDIT_POST = 1106
const val SERVER_OP_GET_TIMELINE_FOR_PROFILE = 1117
const val SERVER_OP_GET_POST = 1118

const val SERVER_OP_GET_PARSED_WEB_LINK = 4007

const val SERVER_OP_EDIT_PROFILE = 1017
const val SERVER_OP_DELETE_PROFILE = 1024

// Player Earnings
const val SERVER_OP_RT_SEND_PLAYER_EARNINGS = 4002
const val SERVER_OP_DO_SHARE_MOVIE = 4004
const val SERVER_OP_DO_SEARCH_USERS = 4005


//Settings
const val SERVER_OP_ST_VERIFY_ACCOUNT = 1018
const val SERVER_OP_ST_CHANGE_ACCOUNT_TYPE = 1019
const val SERVER_OP_ST_GET_BLACKLIST = 1007
const val SERVER_OP_ST_REMOVE_BLACKLIST = 1006
const val SERVER_OP_ST_CHANGE_ACCOUNT_VISIBILITY = 1023

//Wallet
const val SERVER_OP_GET_CURRENCY_RATE_CONVERSION_RATE = 4001

//Invite Friends
const val SERVER_OP_GET_INVITATION_LINK= 1026
const val SERVER_OP_GET_USERS_INVITED= 1025
const val SERVER_OP_DO_SEND_INVITATION= 4003

//Chats
const val SERVER_OP_CHAT_INITIALIZE_ROOM = 1900
const val SERVER_OP_CHAT_SEND_MESSAGE = 1901
const val SERVER_OP_CHAT_UPDATE_LIST = 1902
const val SERVER_OP_CHAT_DELETE_ROOM = 1903
const val SERVER_OP_CHAT_FETCH_MESSAGES = 1904
const val SERVER_OP_CHAT_SEND_USER_ACTIVITY = 1907
const val SERVER_OP_CHAT_HACK = 1909
const val SERVER_OP_CHAT_SET_MESSAGES_READ = 1910
const val SERVER_OP_CHAT_SET_USER_ONLINE = 1913
const val SERVER_OP_CHAT_GET_NEW_CHATS = 1914
const val SERVER_OP_CHAT_GET_NEW_CALLS = 1917
const val SERVER_OP_CHAT_EXPORT_CHATS = 1916


// REAL-TIME COMMUNICATION
const val SERVER_OP_RT_NEW_POST = 1200
const val SERVER_OP_RT_UPDATE_POST = 1201
const val SERVER_OP_RT_DELETE_POST = 1202
const val SERVER_OP_RT_UPDATE_HEARTS = 1203
const val SERVER_OP_RT_UPDATE_SHARES = 1204
const val SERVER_OP_RT_UPDATE_TAGS = 1205
const val SERVER_OP_RT_UPDATE_COMMENTS = 1206
const val SERVER_OP_RT_NEW_SHARE = 1207
const val SERVER_OP_RT_NEW_COMMENT = 1208
const val SERVER_OP_RT_EDIT_POST = 1209
const val SERVER_OP_RT_PUSH_DATA = 1222
const val SERVER_OP_RT_PUSH_CHANNELS = 1223

const val SERVER_OP_RT_CHAT_DELIVERY = 1905
const val SERVER_OP_RT_CHAT_UPDATE_STATUS = 1906
const val SERVER_OP_RT_CHAT_UPDATE_ACTIVITY = 1908
const val SERVER_OP_RT_CHAT_MESSAGE_READ = 1911
const val SERVER_OP_RT_CHAT_MESSAGE_DELIVERED = 1912
const val SERVER_OP_RT_CHAT_DOCUMENT_OPENED = 1915




// ERRORS

const val SERVER_ERROR_SIGNUP_USER_ALREADY_EXISTS = 3000
const val SERVER_ERROR_SIGNIN_EMAIL_NOT_CONFIRMED = 3002
const val SERVER_ERROR_LIST_ALREADY_PRESENT = 3003
const val SERVER_ERROR_USER_NOT_OWNER = 3004
const val SERVER_ERROR_INTEREST_ALREADY_CLAIMED = 3005
const val SERVER_ERROR_SETTINGS_CHANGE_PWD_NO_MATCH_NEW = 3006
const val SERVER_ERROR_SETTINGS_CHANGE_PWD_NO_MATCH_OLD = 3007
const val SERVER_ERROR_SETTINGS_5PL_2_STEP_CONTACTS = 3010
const val SERVER_ERROR_PIC_MODERATION = 3012
const val SERVER_ERROR_SIGNIN_WRONG_PWD = 3014
const val SERVER_ERROR_RECOVERY_NO_EMAIL = 3015
const val SERVER_ERROR_UPLOAD_NO_SIZE = 3017
const val SERVER_ERROR_REDEEM_NOT_ENOUGH_HEARTS = 3018
const val SERVER_ERROR_SESSSION_EXPIRED = 3019
const val SERVER_ERROR_FORCE_LOGOUT = 3020
const val SERVER_ERROR_GENERIC = 3999